---
common-steps:
  - &install_poetry
    run:
      name: Install Poetry
      command: |
        set -e
        source /etc/os-release
        if [[ "$VERSION_CODENAME" == "bullseye" ]]; then
            # Install Poetry via PyPI
            apt-get update && apt-get install --yes --no-install-recommends python3-pip
            pip install poetry==1.6.1
        elif [[ "$VERSION_CODENAME" == "bookworm" ]]; then
            # Install Poetry via system package
            apt-get update && apt-get install --yes --no-install-recommends python3-poetry
        else
            echo "Unsupported Debian version: $VERSION_CODENAME"
            exit 1
        fi

  - &install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        apt-get install --yes --no-install-recommends git gnupg make
        poetry install --no-ansi

  - &install_build_dependencies
    run:
      name: Install build dependencies
      command: |
        set -e
        apt-get update && apt-get install --yes git make sudo

  - &run_unit_tests
    run:
      name: Install requirements and run unit tests
      command: |
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test

  - &run_lint
    run:
      name: Run lint, type checking, code formatting
      command: |
        make lint

  - &check_security
    run:
      name: Run static analysis on source code to find security issues
      command: |
        set -e
        poetry update bandit
        make bandit

  - &check_python_dependencies_for_vulnerabilities
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        set -e
        poetry update safety
        make safety

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download Python wheels
      command: |
        set -x
        mkdir ~/packaging && cd ~/packaging
        # local builds may not have an ssh url, so || true
        git config --global --unset url.ssh://git@github.com.insteadof || true
        git clone https://github.com/freedomofpress/securedrop-builder.git
        cd securedrop-builder
        apt-get update && apt-get install -y sudo make
        make install-deps
        source .venv/bin/activate
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-builder
        export PKG_VERSION=1000.0
        export PKG_PATH=~/project/
        source .venv/bin/activate
        make securedrop-proxy

version: 2.1

jobs:
  build:
    parameters: &parameters
      image:
        type: string
    docker: &docker
      - image: debian:<< parameters.image >>
    steps:
      - checkout
      - *install_build_dependencies
      - *install_packaging_dependencies
      - *verify_requirements
      - *build_debian_package

  unit-test:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *install_poetry
      - *install_testing_dependencies
      - *run_unit_tests
      - store_test_results:
          path: test-results

  lint:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *install_poetry
      - *install_testing_dependencies
      - *run_lint

  check-security:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *install_poetry
      - *install_testing_dependencies
      - *check_security

  check-python-security:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *install_poetry
      - *install_testing_dependencies
      - *check_python_dependencies_for_vulnerabilities


workflows:
  securedrop_proxy_ci:
    jobs: &jobs
      - unit-test:
          matrix: &matrix
            parameters:
              image:
                - bullseye
                - bookworm
      - lint:
          matrix: *matrix
      - check-security:
          matrix: *matrix
      - check-python-security:
          matrix: *matrix
      - build:
          matrix: *matrix

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *jobs
